### PR TITLE
Figure out what to do with deprecated.css and the View/Edit tabs

### PR DESCRIPTION
**Pull request by macburgee1**
We weren't going to add deprecated.css to D8 but the View/Edit tabs at the top of a node relied on it being included in earlier instances of < 5.0.13.

### CODE REVIEW

**Comment by macburgee1** [comment]
Ryan recommends using buttons with a button group.

**Comment by macburgee1** [comment]
**Screenshot 1**
image

**Screenshot 2**
image

**Screenshot 3**
image

**Comment by macburgee1** [comment]
Where unl_five is used, the 'Tabs' block should be moved into the 'Navigation links' region above the 'Main navigation' block:

image

(The region config will be updated when this change is implemented in project_herbie.)

**Review by ericras — COMMENTED** [review]
Let's go ahead and start with this. Possibly circle back around later.

**Pull request merged**
